# -*- coding: utf-8 -*-
"""streamlit_portfolio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-f7tI2KqMwoi-sbOuTzldm3UX4cNLFfD
"""

import streamlit as st

# Title and Contact Info
st.title("Nagapriyatham Pindi's Portfolio")

st.write("""
**Location:** Boston, MA
**Phone:** +1 (857)-321-3941
**Email:** [pindi.n@northeastern.edu](mailto:pindi.n@northeastern.edu)
**LinkedIn:** [LinkedIn Profile](https://www.linkedin.com/in/your-profile)
""")

# Education Section
st.header("Education")
st.write("""
**Northeastern University, Boston, MA**
*Master of Science in Information Systems*
**Expected December 2025**
*Relevant Courses:* Application Engineering and Development, Data Management and Database Design, Data Science Engineering Methods and Tools, Designing Advanced Data Architectures for Business Intelligence.

**CMR College of Engineering and Technology, Hyderabad, India**
*Bachelor of Technology in Computer Science and Engineering*
**June 2022**
*Relevant Courses:* Data Visualization, Data Science, Data structures, Deep Learning, Image Processing, OOPS, Artificial Intelligence, Computer Networks, Design Patterns.
""")

# Skills Section
st.header("Skills")
st.write("""
- **Programming:** Python, SQL, C++, C
- **Databases:** MySQL, Oracle DB, MongoDB
- **Tools:** Tableau, Power BI, Microsoft Excel, Colab, MATLAB, Git, Docker, Azure, Talend, Google BigQuery
- **Python Libraries:** Scikit-Learn, NumPy, Pandas, SciPy, Seaborn, Matplotlib, TensorFlow, Keras
- **Methodology:** Regressions (Robust, Lasso, Ridge, Logistic), Classifications, Clustering
""")

# Work Experience Section
st.header("Work Experience")
st.write("""
**Associate Engineer (Data Analysis)**
*OPENTEXT, Bangalore, India*
**November 2021 – July 2023**
- Improved data processing efficiency by 15% and reduced error rates by 30% through targeted data analysis protocols using Python and SQL.
- Enhanced process efficiency by 40% with automated data analysis tools like Pandas and Tableau.
- Optimized ETL workflows reducing data retrieval times by 25% leveraging tools like Apache Airflow and SQL.

**Data Science Intern**
*SSB Cashew Industries, Odisha, India*
**January 2020 - June 2020**
- Predicted future cashew sales using SARIMA and LSTM models reducing inventory costs by 19%.
- Increased revenue by 22% through customer clustering with K-Means enhancing targeted marketing.
- Improved product quality and customer satisfaction by 30% through sentiment analysis on customer reviews using NLP techniques.
""")

# Projects Section
st.header("Projects")
st.write("""
**Exploring Flight Delays and Cancellations | Tableau EDA | Northeastern University**
- Analyzed data from different datasets from over 100000 flights to uncover trends in delay and cancellation patterns.
- Created over 20 visualizations to provide insights into delays and cancellations enhancing interactivity with calculated fields and parameters.

**Motor Vehicle Collision Analysis | Talend, SQL, Tableau, Power BI | Northeastern University**
- Developed a robust data architecture and ETL workflows using Talend and Alteryx to integrate and analyze collision data from New York, Chicago, and Austin improving data accessibility and reliability.
- Engineered and maintained a dimensional data model enabling dynamic slicing of data.
- Constructed interactive dashboards visualizing key metrics that pinpointed accident hotspots and high-risk times.
- Performed comprehensive data analysis using SQL.

**DNA Classification | Python ML | Northeastern University**
- Extracted DNA dataset from UCI repository conducted pre-processing and feature extraction.
- Developed machine learning algorithms (Naïve Bayes, SVM, Neural Networks, KNN, Random Forest, Decision Tree) and evaluated their performance using accuracy and classification report.
- Conducted comparative analysis and assessed the superior model using metrics.

**New York Airbnb Price Analysis | Power BI EDA | Northeastern University**
- Developed Interactive dashboards to analyze and visualize over 50000 price listings and extracted the key trends and insights that resulted in 15% more engagement and understanding of the data.
- Conducted regression analysis and identified the factors that most significantly impact prices resulting in determining that the factors such as neighborhood, No. of bedrooms, host responses are key drivers of pricing.

**Boston Transportation System | MySQL | Northeastern University**
- Developed a relational database for Boston Transportation optimizing data structures for efficient query processing.
- Implemented security protocols and real-time data features ensuring transactional integrity and user-specific access.
- Crafted data analytics tools to identify trends and inform decisions on ridership and service enhancements.
""")

# Achievements / Leadership Section
st.header("Achievements / Leadership Skills")
st.write("""
- Awarded 'Employee of the Month' for outstanding contributions to a data optimization project that saved the company $50000 annually.
- Mentored junior data analysts providing training on data analysis tools and techniques, improved their performance by 25%.
- Member of Northeastern University's Data Science Club where I coordinated study groups and mentoring sessions.
""")